DROP DATABASE INDIA;
CREATE DATABASE INDIA;
USE INDIA;

CREATE TABLE STATES(
  id TINYINT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(50),
  capital VARCHAR(50),
  population INT,
  largest_city VARCHAR(50),
  formation_date DATE,
  official_language VARCHAR(50),
  districts TINYINT UNSIGNED,
  PRIMARY KEY(id)
);

CREATE TABLE PER_CAPITA_INCOME(
  id TINYINT UNSIGNED AUTO_INCREMENT,
  state_id TINYINT UNSIGNED, 
  2020_21 MEDIUMINT UNSIGNED,
  2021_22 MEDIUMINT UNSIGNED,
  2022_23 MEDIUMINT UNSIGNED,
  PRIMARY KEY(id),
FOREIGN KEY(state_id) 
REFERENCES STATES(id)
);
